:- begin_tests('../src/prolog/stage-structure').
:- ['../src/prolog/stage-structure'].

% test endOfStage, make sure it evaluates as true when wins and losses add to 10
test(endOfStage) :-
    endOfStage(7, 3).
test(endOfStage) :-
    \+endOfStage(8, 0).

% test teamStandings
test(teamStandings) :-
    teamStandings([record(team(newyork), 10, 0, 25, [none], [none], [none]),
    record(team(london), 9, 1, 24, [none], [none], [none]),
    record(team(houston), 8, 2, 23, [none], [none], [none]),
    record(team(boston), 5, 5, 0, [none], [none], [none]),
    record(team(dallas), 6, 4, 10,[none], [none], [none] ),
    record(team(lavaliant), 2, 8, -20, [none], [none], [none]),
    record(team(seoul), 7, 3, 10, [none], [none], [none]),
    record(team(lagladiators), 4, 6, -2, [none], [none], [none]),
    record(team(sanfrancisco), 3, 7, -5, [none], [none], [none]),
    record(team(philadelphia), 6, 4, -2, [none], [none], [none]),
    record(team(shanghai), 0, 10, -25, [none], [none], [none]),
    record(team(florida), 1, 9, -15, [none], [none], [none])],
    [(1, [team(newyork)]),
    (2, [team(london)]),
    (3, [team(houston)]),
    (4, [team(seoul)]),
    (5, [team(dallas)]),
    (6, [team(philadelphia)]),
    (7, [team(boston)]),
    (8, [team(lagladiators)]),
    (9, [team(sanfrancisco)]),
    (10, [team(lavaliant)]),
    (11, [team(florida)]),
    (12, [team(shanghai)])]).
test(teamStandings) :-
    teamStandings([record(team(dallas), 3, 5, -11, [none], [none], [none]),
    record(team(newyork), 8, 0, 21, [none], [none], [none]),
    record(team(shanghai), 0, 8, -30, [none], [none], [none]),
    record(team(philadelphia), 6, 2, -4, [none], [none], [none]),
    record(team(houston), 7, 1, 15, [none], [none], [none]),
    record(team(seoul), 7, 1, 9, [none], [none], [none]),
    record(team(lavaliant), 7, 1, 13, [none], [none], [none]),
    record(team(lagladiators), 4, 4, -10, [none], [none], [none]),
    record(team(sanfrancisco), 3, 5, -8, [none], [none], [none]),
    record(team(florida), 1, 7, -22, [none], [none], [none]),
    record(team(boston), 6, 2, 10, [none], [none], [none]),
    record(team(london), 7, 1, 15, [none], [none], [none])],
    [(1,[team(newyork)]),
    (2,[team(houston),team(london)]),
    (4,[team(lavaliant)]),
    (5,[team(seoul)]),
    (6,[team(boston)]),
    (7,[team(philadelphia)]),
    (8,[team(lagladiators)]),
    (9,[team(sanfrancisco)]),
    (10,[team(dallas)]),
    (11,[team(florida)]),
    (12,[team(shanghai)])]).
test(teamStandings) :-
    teamStandings([record(team(seoul), 6, 0, 14, [none], [none], [none]),
    record(team(newyork), 5, 1, 15, [none], [none], [none]),
    record(team(lagladiators), 4, 2, 10, [none], [none], [none]),
    record(team(london), 4, 2, 8, [none], [none], [none]),
    record(team(lavaliant), 3, 3, 3, [none], [none], [none]),
    record(team(philadelphia), 3, 3, 1, [none], [none], [none]),
    record(team(houston), 3, 3, -3, [none], [none], [none]),
    record(team(dallas), 2, 4, -4, [none], [none], [none]),
    record(team(sanfrancisco), 2, 4, -5, [none], [none], [none]),
    record(team(boston), 2, 4, -8, [none], [none], [none]),
    record(team(florida), 1, 5, -12, [none], [none], [none]),
    record(team(shanghai), 0, 6, -19, [none], [none], [none])],
    [(1, [team(seoul)]),
    (2, [team(newyork)]),
    (3, [team(lagladiators)]),
    (4, [team(london)]),
    (5, [team(lavaliant)]),
    (6, [team(philadelphia)]),
    (7, [team(houston)]),
    (8, [team(dallas)]),
    (9, [team(sanfrancisco)]),
    (10, [team(boston)]),
    (11, [team(florida)]),
    (12, [team(shanghai)])]).
    % Testing a tie for Team Standings
test(teamStandings) :-
    teamStandings([record(team(sanfrancisco), 0, 0, 0, [none], [none], [none]),
    record(team(philadelphia), 0, 0, 0, [none], [none], [none]),
    record(team(houston), 0, 0, 0, [none], [none], [none]),
    record(team(lavaliant), 0, 0, 0, [none], [none], [none]),
    record(team(lagladiators), 0, 0, 0, [none], [none], [none]),
    record(team(shanghai), 0, 0, 0, [none], [none], [none]),
    record(team(boston), 0, 0, 0, [none], [none], [none]),
    record(team(london), 0, 0, 0, [none], [none], [none]),
    record(team(florida), 0, 0, 0, [none], [none], [none]),
    record(team(dallas), 0, 0, 0, [none], [none], [none]),
    record(team(seoul), 0, 0, 0, [none], [none], [none]),
    record(team(newyork), 0, 0, 0, [none], [none], [none])],
    [(1, [team(boston),team(dallas),team(florida),team(houston),team(lagladiators),team(lavaliant),team(london),team(newyork),team(philadelphia),team(sanfrancisco),team(seoul),team(shanghai)])]).
test(teamStandings) :-
    teamStandings([record(team(newyork), 2, 0, 6, [none], [none], [none]),
    record(team(london), 2, 0, 6, [none], [none], [none]),
    record(team(seoul), 2, 0, 6, [none], [none], [none]),
    record(team(boston), 2, 0, 4, [none], [none], [none]),
    record(team(houston), 1, 1, 3, [none], [none], [none]),
    record(team(shanghai), 0, 2, -5, [none], [none], [none]),
    record(team(lagladiators), 1, 1, 3, [none], [none], [none]),
    record(team(lavaliant), 1, 1, 3, [none], [none], [none]),
    record(team(sanfrancisco), 0, 2, -5, [none], [none], [none]),
    record(team(philadelphia), 0, 2, -3, [none], [none], [none]),
    record(team(florida), 0, 2, -4, [none], [none], [none]),
    record(team(dallas), 0, 2, -1, [none], [none], [none])],
    [(1, [team(london),team(newyork),team(seoul)]), (4, [team(boston)]), (5, [team(houston),team(lagladiators),team(lavaliant)]), (8, [team(dallas)]),
    (9, [team(philadelphia)]), (10, [team(florida)]), (11, [team(sanfrancisco),team(shanghai)])]).
test(teamStandings) :-
    teamStandings([record(team(seoul), 4, 0, 10, [none], [none], [none]),
    record(team(philadelphia), 3, 1, 5, [none], [none], [none]),
    record(team(lavaliant), 3, 1, 3, [none], [none], [none]),
    record(team(london), 3, 1, 9, [newyork], [newyork], [none]),
    record(team(houston), 2, 2, 0, [none], [none], [none]),
    record(team(dallas), 2, 2, 0, [none], [none], [none]),
    record(team(shanghai), 0, 4, -13, [none], [none], [none]),
    record(team(florida), 0, 4, -12, [none], [none], [none]),
    record(team(boston), 1, 3, -8, [none], [none], [none]),
    record(team(newyork), 3, 1, 9, [none], [none], [none]),
    record(team(sanfrancisco), 1, 3, -4, [none], [none], [none]),
    record(team(lagladiators), 2, 2, 4, [none], [none], [none])],
    [(1, [team(seoul)]), (2, [team(london)]), (3, [team(newyork)]), (4, [team(philadelphia)]), (5, [team(lavaliant)]), (6, [team(lagladiators)]), (7, [team(dallas), team(houston)]),
    (9, [team(sanfrancisco)]), (10, [team(boston)]), (11, [team(florida)]), (12, [team(shanghai)])]).
test(teamStandings) :-
    teamStandings([record(team(boston), 6, 4, -1, [florida, shanghai, dallas, lavaliant, sanfrancisco, lagladiators], [florida, shanghai, dallas, lavaliant, sanfrancisco, lagladiators], [none]),
    record(team(philadelphia), 7, 3, 12, [boston, florida, houston, shanghai, dallas, lagladiators, lavaliant], [boston, florida, houston, shanghai, dallas, lagladiators, lavaliant], [none]),
    record(team(seoul), 7, 3, 9, [lavaliant, sanfrancisco, dallas, lagladiators, shanghai, philadelphia, florida], [lavaliant, sanfrancisco, dallas, lagladiators, shanghai, philadelphia, florida],
        [none]),
    record(team(dallas), 2, 8, -15, [shanghai, lagladiators], [shanghai, lagladiators], [none]),
    record(team(lagladiators), 6, 4, 9, [sanfrancisco, shanghai, lavaliant, london, houston, florida], [sanfrancisco, shanghai, lavaliant, london, houston, florida], [none]),
    record(team(lavaliant), 4, 6, -5, [shanghai, sanfrancisco, dallas, houston], [shanghai, sanfrancisco, dallas, houston], [none]),
    record(team(florida), 3, 7, -12, [lavaliant, dallas, sanfrancisco], [lavaliant, dallas, sanfrancisco], []),
    record(team(london), 8, 2, 20, [newyork, florida, philadelphia, boston, sanfrancisco, seoul, shanghai, dallas], [newyork, florida, philadelphia, boston, sanfrancisco, seoul, shanghai, dallas],
        [none]),
    record(team(sanfrancisco), 3, 7, -7, [shanghai, dallas, houston], [shanghai, dallas, houston], [none]),
    record(team(shanghai), 0, 10, -35, [none], [none], [none]),
    record(team(houston), 5, 5, 0, [london, boston, florida, shanghai, seoul], [london, boston, florida, shanghai, seoul], [none]),
    record(team(newyork), 9, 1, 25, [florida, boston, houston, philadelphia, sanfrancisco, seoul, shanghai, dallas, lavaliant], [florida, boston, houston, philadelphia, sanfrancisco,
        seoul, shanghai, dallas, lavaliant], [none])],
    [(1, [team(newyork)]),
    (2, [team(london)]),
    (3, [team(philadelphia)]),
    (4, [team(seoul)]),
    (5, [team(lagladiators)]),
    (6, [team(boston)]),
    (7, [team(houston)]),
    (8, [team(lavaliant)]),
    (9, [team(sanfrancisco)]),
    (10, [team(florida)]),
    (11, [team(dallas)]),
    (12, [team(shanghai)])]).

tester() :- teamStandings([record(team(boston), 6, 4, -1, [florida, shanghai, dallas, lavaliant, sanfrancisco, lagladiators], [florida, shanghai, dallas, lavaliant, sanfrancisco, lagladiators], [none]),
    record(team(philadelphia), 7, 3, 12, [boston, florida, houston, shanghai, dallas, lagladiators, lavaliant], [boston, florida, houston, shanghai, dallas, lagladiators, lavaliant], [none]),
    record(team(seoul), 7, 3, 9, [lavaliant, sanfrancisco, dallas, lagladiators, shanghai, philadelphia, florida], [lavaliant, sanfrancisco, dallas, lagladiators, shanghai, philadelphia, florida],
        [none]),
    record(team(dallas), 2, 8, -15, [shanghai, lagladiators], [shanghai, lagladiators], [none]),
    record(team(lagladiators), 6, 4, 9, [sanfrancisco, shanghai, lavaliant, london, houston, florida], [sanfrancisco, shanghai, lavaliant, london, houston, florida], [none]),
    record(team(lavaliant), 4, 6, -5, [shanghai, sanfrancisco, dallas, houston], [shanghai, sanfrancisco, dallas, houston], [none]),
    record(team(florida), 3, 7, -12, [lavaliant, dallas, sanfrancisco], [lavaliant, dallas, sanfrancisco], []),
    record(team(london), 8, 2, 20, [newyork, florida, philadelphia, boston, sanfrancisco, seoul, shanghai, dallas], [newyork, florida, philadelphia, boston, sanfrancisco, seoul, shanghai, dallas],
        [none]),
    record(team(sanfrancisco), 3, 7, -7, [shanghai, dallas, houston], [shanghai, dallas, houston], [none]),
    record(team(shanghai), 0, 10, -35, [none], [none], [none]),
    record(team(houston), 5, 5, 0, [london, boston, florida, shanghai, seoul], [london, boston, florida, shanghai, seoul], [none]),
    record(team(newyork), 9, 1, 25, [florida, boston, houston, philadelphia, sanfrancisco, seoul, shanghai, dallas, lavaliant], [florida, boston, houston, philadelphia, sanfrancisco,
        seoul, shanghai, dallas, lavaliant], [none])], X), print(X).


:- end_tests('../src/prolog/stage-structure').
