:- begin_tests('../src/prolog/stage-structure').
:- ['../src/prolog/stage-structure'].

% test endOfStage, make sure it evaluates as true when wins and losses add to 10
test(endOfStage) :-
    endOfStage(7, 3).
test(endOfStage) :-
    \+endOfStage(8, 0).

% test teamStandings
test(teamStandings) :-
    headToHead(dallas, florida, tie),
    headToHead(dallas, lagladiators, tie),
    headToHead(dallas, lavaliant, tie),
    headToHead(dallas, seoul, tie),
    headToHead(dallas, london, tie),
    headToHead(dallas, houston, tie),
    headToHead(dallas, boston, tie),
    headToHead(dallas, philadelphia, tie),
    headToHead(dallas, shanghai, tie),
    headToHead(dallas, sanfrancisco, tie),
    headToHead(dallas, newyork, tie),
    headToHead(florida, lagladiators, tie),
    headToHead(florida, lavaliant, tie),
    headToHead(florida, seoul, tie),
    headToHead(florida, london, tie),
    headToHead(florida, houston, tie),
    headToHead(florida, boston, tie),
    headToHead(florida, philadelphia, tie),
    headToHead(florida, shanghai, tie),
    headToHead(florida, sanfrancisco, tie),
    headToHead(florida, newyork, tie),
    headToHead(lagladiators, lavaliant, tie),
    headToHead(lagladiators, seoul, tie),
    headToHead(lagladiators, london, tie),
    headToHead(lagladiators, houston, tie),
    headToHead(lagladatiors, boston, tie),
    headToHead(lagladiators, philadelphia, tie),
    headToHead(lagladiators, shanghai, tie),
    headToHead(lagladiators, sanfrancisco, tie),
    headToHead(lagladiators, newyork, tie),
    headToHead(lavaliant, seoul, tie),
    headToHead(lavaliant, london, tie),
    headToHead(lavaliant, houston, tie),
    headToHead(lavaliant, boston, tie),
    headToHead(lavaliant, philadelphia, tie),
    headToHead(lavaliant, shanghai, tie),
    headToHead(lavaliant, sanfrancisco, tie),
    headToHead(lavaliant, newyork, tie),
    headToHead(seoul, london, tie),
    headToHead(seoul, houston, tie),
    headToHead(seoul, boston, tie),
    headToHead(seoul, philadelphia, tie),
    headToHead(seoul, shanghai, tie),
    headToHead(seoul, sanfrancisco, tie),
    headToHead(seoul, newyork, tie),
    headToHead(london, houston, tie),
    headToHead(london, boston, tie),
    headToHead(london, philadelphia, tie),
    headToHead(london, shanghai, tie),
    headToHead(london, sanfrancisco, tie),
    headToHead(london, newyork, tie),
    headToHead(houston, boston, tie),
    headToHead(houston, philadelphia, tie),
    headToHead(houston, shanghai, tie),
    headToHead(houston, sanfrancisco, tie),
    headToHead(houston, newyork, tie),
    headToHead(boston, philadelphia, tie),
    headToHead(boston, shanghai, tie),
    headToHead(boston, sanfrancisco, tie),
    headToHead(boston, newyork, tie),
    headToHead(philadelphia, shanghai, tie),
    headToHead(philadelphia, sanfrancisco, tie),
    headToHead(philadelphia, newyork, tie),
    headToHead(shanghai, sanfrancisco, tie),
    headToHead(shanghai, newyork, tie),
    headToHead(sanfrancisco, newyork, tie),
    
    headToHeadMapDiff(dallas, florida, tie),
    headToHeadMapDiff(dallas, lagladiators, tie),
    headToHeadMapDiff(dallas, lavaliant, tie),
    headToHeadMapDiff(dallas, seoul, tie),
    headToHeadMapDiff(dallas, london, tie),
    headToHeadMapDiff(dallas, houston, tie),
    headToHeadMapDiff(dallas, boston, tie),
    headToHeadMapDiff(dallas, philadelphia, tie),
    headToHeadMapDiff(dallas, shanghai, tie),
    headToHeadMapDiff(dallas, sanfrancisco, tie),
    headToHeadMapDiff(dallas, newyork, tie),
    headToHeadMapDiff(florida, lagladiators, tie),
    headToHeadMapDiff(florida, lavaliant, tie),
    headToHeadMapDiff(florida, seoul, tie),
    headToHeadMapDiff(florida, london, tie),
    headToHeadMapDiff(florida, houston, tie),
    headToHeadMapDiff(florida, boston, tie),
    headToHeadMapDiff(florida, philadelphia, tie),
    headToHeadMapDiff(florida, shanghai, tie),
    headToHeadMapDiff(florida, sanfrancisco, tie),
    headToHeadMapDiff(florida, newyork, tie),
    headToHeadMapDiff(lagladiators, lavaliant, tie),
    headToHeadMapDiff(lagladiators, seoul, tie),
    headToHeadMapDiff(lagladiators, london, tie),
    headToHeadMapDiff(lagladiators, houston, tie),
    headToHeadMapDiff(lagladatiors, boston, tie),
    headToHeadMapDiff(lagladiators, philadelphia, tie),
    headToHeadMapDiff(lagladiators, shanghai, tie),
    headToHeadMapDiff(lagladiators, sanfrancisco, tie),
    headToHeadMapDiff(lagladiators, newyork, tie),
    headToHeadMapDiff(lavaliant, seoul, tie),
    headToHeadMapDiff(lavaliant, london, tie),
    headToHeadMapDiff(lavaliant, houston, tie),
    headToHeadMapDiff(lavaliant, boston, tie),
    headToHeadMapDiff(lavaliant, philadelphia, tie),
    headToHeadMapDiff(lavaliant, shanghai, tie),
    headToHeadMapDiff(lavaliant, sanfrancisco, tie),
    headToHeadMapDiff(lavaliant, newyork, tie),
    headToHeadMapDiff(seoul, london, tie),
    headToHeadMapDiff(seoul, houston, tie),
    headToHeadMapDiff(seoul, boston, tie),
    headToHeadMapDiff(seoul, philadelphia, tie),
    headToHeadMapDiff(seoul, shanghai, tie),
    headToHeadMapDiff(seoul, sanfrancisco, tie),
    headToHeadMapDiff(seoul, newyork, tie),
    headToHeadMapDiff(london, houston, tie),
    headToHeadMapDiff(london, boston, tie),
    headToHeadMapDiff(london, philadelphia, tie),
    headToHeadMapDiff(london, shanghai, tie),
    headToHeadMapDiff(london, sanfrancisco, tie),
    headToHeadMapDiff(london, newyork, tie),
    headToHeadMapDiff(houston, boston, tie),
    headToHeadMapDiff(houston, philadelphia, tie),
    headToHeadMapDiff(houston, shanghai, tie),
    headToHeadMapDiff(houston, sanfrancisco, tie),
    headToHeadMapDiff(houston, newyork, tie),
    headToHeadMapDiff(boston, philadelphia, tie),
    headToHeadMapDiff(boston, shanghai, tie),
    headToHeadMapDiff(boston, sanfrancisco, tie),
    headToHeadMapDiff(boston, newyork, tie),
    headToHeadMapDiff(philadelphia, shanghai, tie),
    headToHeadMapDiff(philadelphia, sanfrancisco, tie),
    headToHeadMapDiff(philadelphia, newyork, tie),
    headToHeadMapDiff(shanghai, sanfrancisco, tie),
    headToHeadMapDiff(shanghai, newyork, tie),
    headToHeadMapDiff(sanfrancisco, newyork, tie),

    teamStandings([record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0),
    record(team(_), 0, 0, 0)],
    [(1, [team(_),team(_),team(_),team(_),team(_),team(_),team(_),team(_),team(_),team(_),team(_),team(_)])]).
test(teamStandings) :- 
    teamStandings([record(team(newyork), 10, 0, 25),
    record(team(london), 9, 1, 24),
    record(team(houston), 8, 2, 23),
    record(team(boston), 5, 5, 0),
    record(team(dallas), 6, 4, 10),
    record(team(lavaliant), 2, 8, -20),
    record(team(seoul), 7, 3, 10),
    record(team(lagladiators), 4, 6, -2),
    record(team(sanfrancisco), 3, 7, -5),
    record(team(philadelphia), 6, 4, -2),
    record(team(shanghai), 0, 10, -25),
    record(team(florida), 1, 9, -15)],
    [(1, [team(newyork)]),
    (2, [team(london)]),
    (3, [team(houston)]),
    (4, [team(seoul)]),
    (5, [team(dallas)]), 
    (6, [team(philadelphia)]),
    (7, [team(boston)]), 
    (8, [team(lagladiators)]), 
    (9, [team(sanfrancisco)]), 
    (10, [team(lavaliant)]), 
    (11, [team(florida)]),
    (12, [team(shanghai)])]).
test(teamStandings) :-
    teamStandings([record(team(dallas), 3, 5, -11),
    record(team(newyork), 8, 0, 21),
    record(team(shanghai), 0, 8, -30),
    record(team(philadelphia), 6, 2, -4),
    record(team(houston), 7, 1, 15),
    record(team(seoul), 7, 1, 9),
    record(team(lavaliant), 7, 1, 13),
    record(team(lagladiators), 4, 4, -10),
    record(team(sanfrancisco), 3, 5, -8),
    record(team(florida), 1, 7, -22),
    record(team(boston), 6, 2, 10),
    record(team(london), 7, 1, 15)],
    [(1,[team(newyork)]),
    (2,[team(houston),team(london)]),
    (3,[team(lavaliant)]),
    (4,[team(seoul)]),
    (5,[team(boston)]),
    (6,[team(philadelphia)]),
    (7,[team(lagladiators)]),
    (8,[team(sanfrancisco)]),
    (9,[team(dallas)]),
    (10,[team(florida)]),
    (11,[team(shanghai)])]).
test(teamStandings) :- 
    teamStandings([record(team(seoul), 6, 0, 14),
    record(team(newyork), 5, 1, 15),
    record(team(lagladiators), 4, 2, 10),
    record(team(london), 4, 2, 8),
    record(team(lavaliant), 3, 3, 3),
    record(team(philadelphia), 3, 3, 1),
    record(team(houston), 3, 3, -3),
    record(team(dallas), 2, 4, -4),
    record(team(sanfrancisco), 2, 4, -5),
    record(team(boston), 2, 4, -8),
    record(team(florida), 1, 5, -12),
    record(team(shanghai), 0, 6, -19)],
    [(1, [team(seoul)]),
    (2, [team(newyork)]),
    (3, [team(lagladiators)]),
    (4, [team(london)]),
    (5, [team(lavaliant)]),
    (6, [team(philadelphia)]),
    (7, [team(houston)]),
    (8, [team(dallas)]),
    (9, [team(sanfrancisco)]),
    (10, [team(boston)]),
    (11, [team(florida)]),
    (12, [team(shanghai)])]).

:- end_tests('../src/prolog/stage-structure').
