% Facts for testing ties

headToHead(dallas, florida, tie).
headToHead(dallas, lagladiators, tie).
headToHead(dallas, lavaliant, tie).
headToHead(dallas, seoul, tie).
headToHead(dallas, london, tie).
headToHead(dallas, houston, tie).
headToHead(dallas, boston, tie).
headToHead(dallas, philadelphia, tie).
headToHead(dallas, shanghai, tie).
headToHead(dallas, sanfrancisco, tie).
headToHead(dallas, newyork, tie).
headToHead(florida, lagladiators, tie).
headToHead(florida, lavaliant, tie).
headToHead(florida, seoul, tie).
headToHead(florida, london, tie).
headToHead(florida, houston, tie).
headToHead(florida, boston, tie).
headToHead(florida, philadelphia, tie).
headToHead(florida, shanghai, tie).
headToHead(florida, sanfrancisco, tie).
headToHead(florida, newyork, tie).
headToHead(lagladiators, lavaliant, tie).
headToHead(lagladiators, seoul, tie).
headToHead(lagladiators, london, tie).
headToHead(lagladiators, houston, tie).
headToHead(lagladiators, boston, tie).
headToHead(lagladiators, philadelphia, tie).
headToHead(lagladiators, shanghai, tie).
headToHead(lagladiators, sanfrancisco, tie).
headToHead(lagladiators, newyork, tie).
headToHead(lavaliant, seoul, tie).
headToHead(lavaliant, london, tie).
headToHead(lavaliant, houston, tie).
headToHead(lavaliant, boston, tie).
headToHead(lavaliant, philadelphia, tie).
headToHead(lavaliant, shanghai, tie).
headToHead(lavaliant, sanfrancisco, tie).
headToHead(lavaliant, newyork, tie).
headToHead(seoul, london, tie).
headToHead(seoul, houston, tie).
headToHead(seoul, boston, tie).
headToHead(seoul, philadelphia, tie).
headToHead(seoul, shanghai, tie).
headToHead(seoul, sanfrancisco, tie).
headToHead(seoul, newyork, tie).
headToHead(london, houston, tie).
headToHead(london, boston, tie).
headToHead(london, philadelphia, tie).
headToHead(london, shanghai, tie).
headToHead(london, sanfrancisco, tie).
headToHead(london, newyork, tie).
headToHead(houston, philadelphia, tie).
headToHead(houston, shanghai, tie).
headToHead(houston, sanfrancisco, tie).
headToHead(houston, newyork, tie).
headToHead(boston, philadelphia, tie).
headToHead(boston, shanghai, tie).
headToHead(boston, sanfrancisco, tie).
headToHead(boston, newyork, tie).
headToHead(philadelphia, shanghai, tie).
headToHead(philadelphia, sanfrancisco, tie).
headToHead(philadelphia, newyork, tie).
headToHead(shanghai, sanfrancisco, tie).
headToHead(shanghai, newyork, tie).
headToHead(sanfrancisco, newyork, tie).

headToHead(X, Y, X) :- X @> Y, headToHead(Y, X, X).
headToHead(X, Y, tie) :- X @> Y, headToHead(Y, X, tie).


headToHeadMapDiff(dallas, florida, tie).
headToHeadMapDiff(dallas, lagladiators, tie).
headToHeadMapDiff(dallas, lavaliant, tie).
headToHeadMapDiff(dallas, seoul, tie).
headToHeadMapDiff(dallas, london, tie).
headToHeadMapDiff(dallas, houston, tie).
headToHeadMapDiff(dallas, boston, tie).
headToHeadMapDiff(dallas, philadelphia, tie).
headToHeadMapDiff(dallas, shanghai, tie).
headToHeadMapDiff(dallas, sanfrancisco, tie).
headToHeadMapDiff(dallas, newyork, tie).
headToHeadMapDiff(florida, lagladiators, tie).
headToHeadMapDiff(florida, lavaliant, tie).
headToHeadMapDiff(florida, seoul, tie).
headToHeadMapDiff(florida, london, tie).
headToHeadMapDiff(florida, houston, tie).
headToHeadMapDiff(florida, boston, tie).
headToHeadMapDiff(florida, philadelphia, tie).
headToHeadMapDiff(florida, shanghai, tie).
headToHeadMapDiff(florida, sanfrancisco, tie).
headToHeadMapDiff(florida, newyork, tie).
headToHeadMapDiff(lagladiators, lavaliant, tie).
headToHeadMapDiff(lagladiators, seoul, tie).
headToHeadMapDiff(lagladiators, london, tie).
headToHeadMapDiff(lagladiators, houston, tie).
headToHeadMapDiff(lagladiators, boston, tie).
headToHeadMapDiff(lagladiators, philadelphia, tie).
headToHeadMapDiff(lagladiators, shanghai, tie).
headToHeadMapDiff(lagladiators, sanfrancisco, tie).
headToHeadMapDiff(lagladiators, newyork, tie).
headToHeadMapDiff(lavaliant, seoul, tie).
headToHeadMapDiff(lavaliant, london, tie).
headToHeadMapDiff(lavaliant, houston, tie).
headToHeadMapDiff(lavaliant, boston, tie).
headToHeadMapDiff(lavaliant, philadelphia, tie).
headToHeadMapDiff(lavaliant, shanghai, tie).
headToHeadMapDiff(lavaliant, sanfrancisco, tie).
headToHeadMapDiff(lavaliant, newyork, tie).
headToHeadMapDiff(seoul, london, tie).
headToHeadMapDiff(seoul, houston, tie).
headToHeadMapDiff(seoul, boston, tie).
headToHeadMapDiff(seoul, philadelphia, tie).
headToHeadMapDiff(seoul, shanghai, tie).
headToHeadMapDiff(seoul, sanfrancisco, tie).
headToHeadMapDiff(seoul, newyork, tie).
headToHeadMapDiff(london, houston, tie).
headToHeadMapDiff(london, boston, tie).
headToHeadMapDiff(london, philadelphia, tie).
headToHeadMapDiff(london, shanghai, tie).
headToHeadMapDiff(london, sanfrancisco, tie).
headToHeadMapDiff(london, newyork, tie).
headToHeadMapDiff(houston, boston, tie).
headToHeadMapDiff(houston, philadelphia, tie).
headToHeadMapDiff(houston, shanghai, tie).
headToHeadMapDiff(houston, sanfrancisco, tie).
headToHeadMapDiff(houston, newyork, tie).
headToHeadMapDiff(boston, philadelphia, tie).
headToHeadMapDiff(boston, shanghai, tie).
headToHeadMapDiff(boston, sanfrancisco, tie).
headToHeadMapDiff(boston, newyork, tie).
headToHeadMapDiff(philadelphia, shanghai, tie).
headToHeadMapDiff(philadelphia, sanfrancisco, tie).
headToHeadMapDiff(philadelphia, newyork, tie).
headToHeadMapDiff(shanghai, sanfrancisco, tie).
headToHeadMapDiff(shanghai, newyork, tie).
headToHeadMapDiff(sanfrancisco, newyork, tie).

headToHeadMapDiff(X, Y, X) :- X @> Y, headToHeadMapDiff(Y, X, X).
headToHeadMapDiff(X, Y, tie) :- X @>Y, headToHeadMapDiff(Y, X, tie).
