:- begin_tests('../../prolog/stage-structure').
:- ['../../prolog/stage-structure'].
:- use_module(library(http/json)).


% Tests for aFullOWLSeason

%test(aFullOWLSeason) :-
%tester() :-
testAbduction(OverallRecords, OverallStandings) :-
    open('abduction-test-data.json', read, File), json_read(File, Result1), json_read(File, Result2), json_read(File, Result3), json_read(File, Result4),
        extractScheduleFromJson([Result1, Result2, Result3, Result4], Schedule),

    aFullOWLSeason([record(team(sanfrancisco), 0, 0, 0, [london-(0), houston-(0), dallas-(0), newyork-(0), philadelphia-(0), lavaliant-(0),
    lagladiators-(0), seoul-(0), shanghai-(0), boston-(0), florida-(0)], [london-(0), houston-(0), dallas-(0), newyork-(0), philadelphia-(0), lavaliant-(0),
    lagladiators-(0), seoul-(0), shanghai-(0), boston-(0), florida-(0)], [none]),
    record(team(philadelphia), 0, 0, 0, [london-(0), houston-(0), dallas-(0), newyork-(0), sanfrancisco-(0), lavaliant-(0), lagladiators-(0),
    seoul-(0), shanghai-(0), boston-(0), florida-(0)], [london-(0), houston-(0), dallas-(0), newyork-(0), sanfrancisco-(0), lavaliant-(0),
    lagladiators-(0), seoul-(0), shanghai-(0), boston-(0), florida-(0)], [none]),
    record(team(houston), 0, 0, 0, [london-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), lavaliant-(0), lagladiators-(0),
    seoul-(0), shanghai-(0), boston-(0), florida-(0)], [london-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), lavaliant-(0),
    lagladiators-(0), seoul-(0), shanghai-(0), boston-(0), florida-(0)], [none]),
    record(team(lavaliant), 0, 0, 0, [london-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0), lagladiators-(0),
    seoul-(0), shanghai-(0), boston-(0), florida-(0)], [london-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0),
    lagladiators-(0), seoul-(0), shanghai-(0), boston-(0), florida-(0)], [none]),
    record(team(lagladiators), 0, 0, 0, [london-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0), lavaliant-(0),
    seoul-(0), shanghai-(0), boston-(0), florida-(0)], [london-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0),
    lavaliant-(0), seoul-(0), shanghai-(0), boston-(0), florida-(0)], [none]),
    record(team(shanghai), 0, 0, 0, [london-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0), lavaliant-(0),
    seoul-(0), lagladiators-(0), boston-(0), florida-(0)], [london-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0),
    lavaliant-(0), seoul-(0), lagladiators-(0), boston-(0), florida-(0)], [none]),
    record(team(boston), 0, 0, 0, [london-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0), lavaliant-(0),
    seoul-(0), lagladiators-(0), shanghai-(0), florida-(0)], [london-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0),
    lavaliant-(0), seoul-(0), lagladiators-(0), shanghai-(0), florida-(0)], [none]),
    record(team(london), 0, 0, 0, [boston-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0), lavaliant-(0),
    seoul-(0), lagladiators-(0), shanghai-(0), florida-(0)], [boston-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0),
    lavaliant-(0), seoul-(0), lagladiators-(0), shanghai-(0), florida-(0)], [none]),
    record(team(florida), 0, 0, 0, [boston-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0), lavaliant-(0),
    seoul-(0), lagladiators-(0), shanghai-(0), london-(0)], [boston-(0), philadelphia-(0), dallas-(0), newyork-(0), sanfrancisco-(0), houston-(0),
    lavaliant-(0), seoul-(0), lagladiators-(0), shanghai-(0), london-(0)], [none]),
    record(team(dallas), 0, 0, 0, [boston-(0), philadelphia-(0), florida-(0), newyork-(0), sanfrancisco-(0), houston-(0), lavaliant-(0),
    seoul-(0), lagladiators-(0), shanghai-(0), london-(0)], [boston-(0), philadelphia-(0), florida-(0), newyork-(0), sanfrancisco-(0), houston-(0),
    lavaliant-(0), seoul-(0), lagladiators-(0), shanghai-(0), london-(0)], [none]),
    record(team(seoul), 0, 0, 0, [boston-(0), philadelphia-(0), florida-(0), newyork-(0), sanfrancisco-(0), houston-(0), lavaliant-(0),
    dallas-(0), lagladiators-(0), shanghai-(0), london-(0)], [boston-(0), philadelphia-(0), florida-(0), newyork-(0), sanfrancisco-(0), houston-(0),
    lavaliant-(0), dallas-(0), lagladiators-(0), shanghai-(0), london-(0)], [none]),
    record(team(newyork), 0, 0, 0, [boston-(0), philadelphia-(0), florida-(0), seoul-(0), sanfrancisco-(0), houston-(0), lavaliant-(0),
    dallas-(0), lagladiators-(0), shanghai-(0), london-(0)], [boston-(0), philadelphia-(0), florida-(0), seoul-(0), sanfrancisco-(0), houston-(0),
    lavaliant-(0), dallas-(0), lagladiators-(0), shanghai-(0), london-(0)], [none])], Schedule, /*List of StageRecords*/_,
    % OverallRecords
    /*[record(team(boston),26,14,28,[dallas-6,florida-13,houston- -3,lagladiators-7,lavaliant-5,london- -3,newyork- -3,philadelphia- -1,sanfrancisco- -2,seoul- -1,shanghai-10],
        [dallas-2,florida-4,houston- -2,lagladiators-3,lavaliant-2,london-0,newyork-0,philadelphia-0,sanfrancisco- -1,seoul-1,shanghai-3],[]),
    record(team(dallas),12,28,-42,[boston- -6,florida-1,houston- -9,lagladiators- -2,lavaliant- -4,london- -2,newyork- -7,philadelphia- -8,sanfrancisco- -6,seoul- -6,shanghai-7],
        [boston- -2,florida- -1,houston- -3,lagladiators-0,lavaliant- -2,london- -1,newyork- -3,philadelphia- -2,sanfrancisco- -2,seoul- -4,shanghai-4],[]),
    record(team(florida),7,33,-78,[boston- -13,dallas- -1,houston- -9,lagladiators- -10,lavaliant- -4,london- -11,newyork- -12,philadelphia- -11,sanfrancisco- -7,seoul- -7,shanghai-7],
        [boston- -4,dallas-1,houston- -4,lagladiators- -4,lavaliant- -2,london- -4,newyork- -4,philadelphia- -4,sanfrancisco- -1,seoul- -3,shanghai-3],[]),
    record(team(houston),22,18,17,[boston-3,dallas-9,florida-9,lagladiators-0,lavaliant- -6,london-8,newyork- -8,philadelphia- -1,sanfrancisco- -5,seoul- -3,shanghai-11],
        [boston-2,dallas-3,florida-4,lagladiators- -2,lavaliant- -1,london-4,newyork- -4,philadelphia- -2,sanfrancisco- -2,seoul- -1,shanghai-3],[]),
    record(team(lagladiators),25,15,24,[boston- -7,dallas-2,florida-10,houston-0,lavaliant- -1,london-4,newyork- -4,philadelphia-1,sanfrancisco-6,seoul- -3,shanghai-16],
        [boston- -3,dallas-0,florida-4,houston-2,lavaliant- -2,london-3,newyork- -1,philadelphia-1,sanfrancisco-2,seoul-0,shanghai-4],[]),
    record(team(lavaliant),27,13,36,[boston- -5,dallas-4,florida-4,houston-6,lagladiators-1,london- -1,newyork- -6,philadelphia-4,sanfrancisco-12,seoul-4,shanghai-13],
        [boston- -2,dallas-2,florida-2,houston-1,lagladiators-2,london- -1,newyork- -1,philadelphia-1,sanfrancisco-4,seoul-2,shanghai-4],[]),
    record(team(london),24,16,33,[boston-3,dallas-2,florida-11,houston- -8,lagladiators- -4,lavaliant-1,newyork- -6,philadelphia-5,sanfrancisco-9,seoul-10,shanghai-10],
        [boston-0,dallas-1,florida-4,houston- -4,lagladiators- -3,lavaliant-1,newyork- -2,philadelphia-0,sanfrancisco-4,seoul-4,shanghai-3],[]),
    record(team(newyork),34,6,83,[boston-3,dallas-7,florida-12,houston-8,lagladiators-4,lavaliant-6,london-6,philadelphia-6,sanfrancisco-7,seoul-10,shanghai-14],
        [boston-0,dallas-3,florida-4,houston-4,lagladiators-1,lavaliant-1,london-2,philadelphia-2,sanfrancisco-3,seoul-4,shanghai-4],[]),
    record(team(philadelphia),24,16,13,[boston-1,dallas-8,florida-11,houston-1,lagladiators- -1,lavaliant- -4,london- -5,newyork- -6,sanfrancisco-0,seoul- -2,shanghai-10],
        [boston-0,dallas-2,florida-4,houston-2,lagladiators- -1,lavaliant- -1,london-0,newyork- -2,sanfrancisco-1,seoul- -1,shanghai-4],[]),
    record(team(sanfrancisco),17,23,-7,[boston-2,dallas-6,florida-7,houston-5,lagladiators- -6,lavaliant- -12,london- -9,newyork- -7,philadelphia-0,seoul- -5,shanghai-12],
        [boston-1,dallas-2,florida-1,houston-2,lagladiators- -2,lavaliant- -4,london- -4,newyork- -3,philadelphia- -1,seoul- -2,shanghai-4],[]),
    record(team(seoul),22,18,13,[boston-1,dallas-6,florida-7,houston-3,lagladiators-3,lavaliant- -4,london- -10,newyork- -10,philadelphia-2,sanfrancisco-5,shanghai-10],
        [boston- -1,dallas-4,florida-3,houston-1,lagladiators-0,lavaliant- -2,london- -4,newyork- -4,philadelphia-1,sanfrancisco-2,shanghai-4],[]),
    record(team(shanghai),0,40,-120,[boston- -10,dallas- -7,florida- -7,houston- -11,lagladiators- -16,lavaliant- -13,london- -10,newyork- -14,philadelphia- -10,sanfrancisco- -12,seoul- -10],
        [boston- -3,dallas- -4,florida- -3,houston- -3,lagladiators- -4,lavaliant- -4,london- -3,newyork- -4,philadelphia- -4,sanfrancisco- -4,seoul- -4],[])],
    % OverallStandings
    [(1,[team(newyork)]),
    (2,[team(lavaliant)]),
    (3,[team(boston)]),
    (4,[team(lagladiators)]),
    (5,[team(london)]),
    (6,[team(philadelphia)]),
    (7,[team(houston)]),
    (8,[team(seoul)]),
    (9,[team(sanfrancisco)]),
    (10,[team(dallas)]),
    (11,[team(florida)]),
    (12,[team(shanghai)])]).*/
    OverallRecords, OverallStandings).

:- end_tests('../../prolog/stage-structure').
