:- begin_tests('../../prolog/stage-structure').
:- ['../../prolog/stage-structure'].
:- use_module(library(http/json)).


% Tests for aFullOWLSeason

test(aFullOWLSeason) :-
    open('results.json', read, File), json_read(File, Result1), json_read(File, Result2), json_read(File, Result3), json_read(File, Result4),  
        extractScheduleFromJson([Result1, Result2, Result3, Result4], Schedule),
    
    aFullOWLSeason([record(team(sanfrancisco), 0, 0, 0, [[london, 0], [houston, 0], [dallas, 0], [newyork, 0], [philadelphia, 0], [lavaliant, 0],
    [lagladiators, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [[london, 0], [houston, 0], [dallas, 0], [newyork, 0], [philadelphia, 0], [lavaliant, 0],
    [lagladiators, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [none]),
    record(team(philadelphia), 0, 0, 0, [[london, 0], [houston, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [lavaliant, 0], [lagladiators, 0],
    [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [[london, 0], [houston, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [lavaliant, 0],
    [lagladiators, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [none]),
    record(team(houston), 0, 0, 0, [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [lavaliant, 0], [lagladiators, 0],
    [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [lavaliant, 0],
    [lagladiators, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [none]),
    record(team(lavaliant), 0, 0, 0, [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lagladiators, 0],
    [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lagladiators, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [none]),
    record(team(lagladiators), 0, 0, 0, [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [none]),
    record(team(shanghai), 0, 0, 0, [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [lagladiators, 0], [boston, 0], [florida, 0]], [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [lagladiators, 0], [boston, 0], [florida, 0]], [none]),
    record(team(boston), 0, 0, 0, [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [lagladiators, 0], [shanghai, 0], [florida, 0]], [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [lagladiators, 0], [shanghai, 0], [florida, 0]], [none]),
    record(team(london), 0, 0, 0, [[boston, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [lagladiators, 0], [shanghai, 0], [florida, 0]], [[boston, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [lagladiators, 0], [shanghai, 0], [florida, 0]], [none]),
    record(team(florida), 0, 0, 0, [[boston, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [[boston, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [none]),
    record(team(dallas), 0, 0, 0, [[boston, 0], [philadelphia, 0], [florida, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [[boston, 0], [philadelphia, 0], [florida, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [none]),
    record(team(seoul), 0, 0, 0, [[boston, 0], [philadelphia, 0], [florida, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [dallas, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [[boston, 0], [philadelphia, 0], [florida, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [dallas, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [none]),
    record(team(newyork), 0, 0, 0, [[boston, 0], [philadelphia, 0], [florida, 0], [seoul, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [dallas, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [[boston, 0], [philadelphia, 0], [florida, 0], [seoul, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [dallas, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [none])], Schedule, _,
    [record(team(boston),26,14,28,[[florida,13],[newyork,-3],[shanghai,10],[seoul,-1],[sanfrancisco,-2],[london,-3],[lavaliant,5],[dallas,6],[houston,-3],[philadelphia,-1],[lagladiators,7]],
    [[florida,4],[newyork,0],[shanghai,3],[seoul,1],[sanfrancisco,-1],[london,0],[lavaliant,2],[dallas,2],[houston,-2],[philadelphia,0],[lagladiators,3]],[]),
    record(team(dallas),12,28,-42,[[lavaliant,-4],[seoul,-6],[florida,1],[houston,-9],[london,-2],[sanfrancisco,-6],[philadelphia,-8],[boston,-6],[lagladiators,-2],[shanghai,7],[newyork,-7]],
    [[lavaliant,-2],
    [seoul,-4],[florida,-1],[houston,-3],[london,-1],[sanfrancisco,-2],[philadelphia,-2],[boston,-2],[lagladiators,0],[shanghai,4],[newyork,-3]],[]),
    record(team(florida),7,33,-78,[[boston,-13],[london,-11],[dallas,-1],[shanghai,7],[houston,-9],[seoul,-7],[lagladiators,-10],[lavaliant,-4],[philadelphia,-11],[newyork,-12],[sanfrancisco,-7]],
    [[boston,-4],
    [london,-4],[dallas,1],[shanghai,3],[houston,-4],[seoul,-3],[lagladiators,-4],[lavaliant,-2],[philadelphia,-4],[newyork,-4],[sanfrancisco,-1]],[]),
    record(team(houston),22,18,17,[[newyork,-8],[philadelphia,-1],[lavaliant,-6],[dallas,9],[florida,9],[shanghai,11],[sanfrancisco,-5],[lagladiators,0],[boston,3],[london,8],[seoul,-3]],
    [[newyork,-4],[philadelphia,-2],
    [lavaliant,-1],[dallas,3],[florida,4],[shanghai,3],[sanfrancisco,-2],[lagladiators,-2],[boston,2],[london,4],[seoul,-1]],[]),
    record(team(lagladiators),25,15,24,[[seoul,-3],[shanghai,16],[london,4],[newyork,-4],[philadelphia,1],[lavaliant,-1],[florida,10],[houston,0],[dallas,2],[sanfrancisco,6],[boston,-7]],[[seoul,0],
    [shanghai,4],
    [london,3],[newyork,-1],[philadelphia,1],[lavaliant,-2],[florida,4],[houston,2],[dallas,0],[sanfrancisco,2],[boston,-3]],[]),
    record(team(lavaliant),27,13,36,[[dallas,4],[sanfrancisco,12],[houston,6],[london,-1],[newyork,-6],[lagladiators,1],[boston,-5],[florida,4],[shanghai,13],[seoul,4],[philadelphia,4]],[[dallas,2],
    [sanfrancisco,4],[houston,1],
    [london,-1],[newyork,-1],[lagladiators,2],[boston,-2],[florida,2],[shanghai,4],[seoul,2],[philadelphia,1]],[]),
    record(team(london),24,16,33,[[philadelphia,5],[florida,11],[lagladiators,-4],[lavaliant,1],[dallas,2],[boston,3],[seoul,10],[sanfrancisco,9],[newyork,-6],[houston,-8],[shanghai,10]],
    [[philadelphia,0],[florida,4],
    [lagladiators,-3],[lavaliant,1],[dallas,1],[boston,0],[seoul,4],[sanfrancisco,4],[newyork,-2],[houston,-4],[shanghai,3]],[]),
    record(team(newyork),34,6,83,[[houston,8],[boston,3],[sanfrancisco,7],[lagladiators,4],[lavaliant,6],[philadelphia,6],[shanghai,14],[seoul,10],[london,6],[florida,12],[dallas,7]],[[houston,4],
    [boston,0],[sanfrancisco,3],
    [lagladiators,1],[lavaliant,1],[philadelphia,2],[shanghai,4],[seoul,4],[london,2],[florida,4],[dallas,3]],[]),
    record(team(philadelphia),24,16,13,[[london,-5],[houston,1],[seoul,-2],[sanfrancisco,0],[lagladiators,-1],[newyork,-6],[dallas,8],[shanghai,10],[florida,11],[boston,1],[lavaliant,-4]],[
    [london,0],[houston,2],
    [seoul,-1],[sanfrancisco,1],[lagladiators,-1],[newyork,-2],[dallas,2],[shanghai,4],[florida,4],[boston,0],[lavaliant,-1]],[]),
    record(team(sanfrancisco),17,23,-7,[[shanghai,12],[lavaliant,-12],[newyork,-7],[philadelphia,0],[boston,2],[dallas,6],[houston,5],[london,-9],[seoul,-5],[lagladiators,-6],[florida,7]],
    [[shanghai,4],[lavaliant,-4],
    [newyork,-3],[philadelphia,-1],[boston,1],[dallas,2],[houston,2],[london,-4],[seoul,-2],[lagladiators,-2],[florida,1]],[]),
    record(team(seoul),22,18,13,[[lagladiators,3],[dallas,6],[philadelphia,2],[boston,1],[florida,7],[shanghai,10],[london,-10],[newyork,-10],[sanfrancisco,5],[lavaliant,-4],[houston,3]],
    [[lagladiators,0],[dallas,4],
    [philadelphia,1],[boston,-1],[florida,3],[shanghai,4],[london,-4],[newyork,-4],[sanfrancisco,2],[lavaliant,-2],[houston,1]],[]),record(team(shanghai),0,40,-120,[[sanfrancisco,-12],
    [lagladiators,-16],[boston,-10],
    [florida,-7],[houston,-11],[seoul,-10],[newyork,-14],[philadelphia,-10],[lavaliant,-13],[dallas,-7],[london,-10]],[[sanfrancisco,-4],[lagladiators,-4],[boston,-3],[florida,-3],[houston,-3],
    [seoul,-4],
    [newyork,-4],[philadelphia,-4],[lavaliant,-4],[london,-3],[dallas,-4]],[])],
    [(1,[team(newyork)]),
    (2,[team(lavaliant)]),
    (3,[team(boston)]),
    (4,[team(lagladiators)]),
    (5,[team(london)]),
    (6,[team(philadelphia)]),
    (7,[team(houston)]),
    (8,[team(seoul)]),
    (9,[team(sanfrancisco)]),
    (10,[team(dallas)]),
    (11,[team(florida)]),
    (12,[team(shanghai)])]).
