:- begin_tests('../../prolog/stage-structure').
:- ['../../prolog/stage-structure'].

% test endOfStage, make sure it evaluates as true when wins and losses add to 10
test(endOfStage) :-
    endOfStage(7, 3).
test(endOfStage) :-
    \+endOfStage(8, 0).

% test teamStandings
test(teamStandings) :-
    teamStandings([record(team(newyork), 10, 0, 25, [none], [none], [none]),
    record(team(london), 9, 1, 24, [none], [none], [none]),
    record(team(houston), 8, 2, 23, [none], [none], [none]),
    record(team(boston), 5, 5, 0, [none], [none], [none]),
    record(team(dallas), 6, 4, 10,[none], [none], [none] ),
    record(team(lavaliant), 2, 8, -20, [none], [none], [none]),
    record(team(seoul), 7, 3, 10, [none], [none], [none]),
    record(team(lagladiators), 4, 6, -2, [none], [none], [none]),
    record(team(sanfrancisco), 3, 7, -5, [none], [none], [none]),
    record(team(philadelphia), 6, 4, -2, [none], [none], [none]),
    record(team(shanghai), 0, 10, -25, [none], [none], [none]),
    record(team(florida), 1, 9, -15, [none], [none], [none])],
    [(1, [team(newyork)]),
    (2, [team(london)]),
    (3, [team(houston)]),
    (4, [team(seoul)]),
    (5, [team(dallas)]),
    (6, [team(philadelphia)]),
    (7, [team(boston)]),
    (8, [team(lagladiators)]),
    (9, [team(sanfrancisco)]),
    (10, [team(lavaliant)]),
    (11, [team(florida)]),
    (12, [team(shanghai)])]).
test(teamStandings) :-
    teamStandings([record(team(dallas), 3, 5, -11, [none], [none], [none]),
    record(team(newyork), 8, 0, 21, [none], [none], [none]),
    record(team(shanghai), 0, 8, -30, [none], [none], [none]),
    record(team(philadelphia), 6, 2, -4, [none], [none], [none]),
    record(team(houston), 7, 1, 15, [[london, 0]], [[london, 0]], [none]),
    record(team(seoul), 7, 1, 9, [none], [none], [none]),
    record(team(lavaliant), 7, 1, 13, [none], [none], [none]),
    record(team(lagladiators), 4, 4, -10, [none], [none], [none]),
    record(team(sanfrancisco), 3, 5, -8, [none], [none], [none]),
    record(team(florida), 1, 7, -22, [none], [none], [none]),
    record(team(boston), 6, 2, 10, [none], [none], [none]),
    record(team(london), 7, 1, 15, [[houston, 0]], [[houston, 0]], [none])],
    [(1,[team(newyork)]),
    (2,[team(houston),team(london)]),
    (4,[team(lavaliant)]),
    (5,[team(seoul)]),
    (6,[team(boston)]),
    (7,[team(philadelphia)]),
    (8,[team(lagladiators)]),
    (9,[team(sanfrancisco)]),
    (10,[team(dallas)]),
    (11,[team(florida)]),
    (12,[team(shanghai)])]).
test(teamStandings) :-
    teamStandings([record(team(seoul), 6, 0, 14, [none], [none], [none]),
    record(team(newyork), 5, 1, 15, [none], [none], [none]),
    record(team(lagladiators), 4, 2, 10, [none], [none], [none]),
    record(team(london), 4, 2, 8, [none], [none], [none]),
    record(team(lavaliant), 3, 3, 3, [none], [none], [none]),
    record(team(philadelphia), 3, 3, 1, [none], [none], [none]),
    record(team(houston), 3, 3, -3, [none], [none], [none]),
    record(team(dallas), 2, 4, -4, [none], [none], [none]),
    record(team(sanfrancisco), 2, 4, -5, [none], [none], [none]),
    record(team(boston), 2, 4, -8, [none], [none], [none]),
    record(team(florida), 1, 5, -12, [none], [none], [none]),
    record(team(shanghai), 0, 6, -19, [none], [none], [none])],
    [(1, [team(seoul)]),
    (2, [team(newyork)]),
    (3, [team(lagladiators)]),
    (4, [team(london)]),
    (5, [team(lavaliant)]),
    (6, [team(philadelphia)]),
    (7, [team(houston)]),
    (8, [team(dallas)]),
    (9, [team(sanfrancisco)]),
    (10, [team(boston)]),
    (11, [team(florida)]),
    (12, [team(shanghai)])]).
    % Testing a tie for Team Standings
test(teamStandings) :-
    teamStandings([record(team(sanfrancisco), 0, 0, 0, [[london, 0], [houston, 0], [dallas, 0], [newyork, 0], [philadelphia, 0], [lavaliant, 0],
    [lagladiators, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [[london, 0], [houston, 0], [dallas, 0], [newyork, 0], [philadelphia, 0], [lavaliant, 0],
    [lagladiators, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [none]),
    record(team(philadelphia), 0, 0, 0, [[london, 0], [houston, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [lavaliant, 0], [lagladiators, 0],
    [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [[london, 0], [houston, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [lavaliant, 0],
    [lagladiators, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [none]),
    record(team(houston), 0, 0, 0, [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [lavaliant, 0], [lagladiators, 0],
    [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [lavaliant, 0],
    [lagladiators, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [none]),
    record(team(lavaliant), 0, 0, 0, [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lagladiators, 0],
    [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lagladiators, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [none]),
    record(team(lagladiators), 0, 0, 0, [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [shanghai, 0], [boston, 0], [florida, 0]], [none]),
    record(team(shanghai), 0, 0, 0, [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [lagladiators, 0], [boston, 0], [florida, 0]], [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [lagladiators, 0], [boston, 0], [florida, 0]], [none]),
    record(team(boston), 0, 0, 0, [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [lagladiators, 0], [shanghai, 0], [florida, 0]], [[london, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [lagladiators, 0], [shanghai, 0], [florida, 0]], [none]),
    record(team(london), 0, 0, 0, [[boston, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [lagladiators, 0], [shanghai, 0], [florida, 0]], [[boston, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [lagladiators, 0], [shanghai, 0], [florida, 0]], [none]),
    record(team(florida), 0, 0, 0, [[boston, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [[boston, 0], [philadelphia, 0], [dallas, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [none]),
    record(team(dallas), 0, 0, 0, [[boston, 0], [philadelphia, 0], [florida, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [seoul, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [[boston, 0], [philadelphia, 0], [florida, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [seoul, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [none]),
    record(team(seoul), 0, 0, 0, [[boston, 0], [philadelphia, 0], [florida, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [dallas, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [[boston, 0], [philadelphia, 0], [florida, 0], [newyork, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [dallas, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [none]),
    record(team(newyork), 0, 0, 0, [[boston, 0], [philadelphia, 0], [florida, 0], [seoul, 0], [sanfrancisco, 0], [houston, 0], [lavaliant, 0],
    [dallas, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [[boston, 0], [philadelphia, 0], [florida, 0], [seoul, 0], [sanfrancisco, 0], [houston, 0],
    [lavaliant, 0], [dallas, 0], [lagladiators, 0], [shanghai, 0], [london, 0]], [none])],
    [(1, [team(boston),team(dallas),team(florida),team(houston),team(lagladiators),team(lavaliant),team(london),team(newyork),team(philadelphia),team(sanfrancisco),team(seoul),team(shanghai)])]).
test(teamStandings) :-
    teamStandings([record(team(newyork), 2, 0, 6, [[london, 0], [seoul, 0]], [[london, 0], [seoul, 0]], [none]),
    record(team(london), 2, 0, 6, [[newyork, 0], [seoul, 0]], [[newyork, 0], [seoul, 0]], [none]),
    record(team(seoul), 2, 0, 6, [[newyork, 0], [london, 0]], [[newyork, 0], [london, 0]], [none]),
    record(team(boston), 2, 0, 4, [none], [none], [none]),
    record(team(houston), 1, 1, 3, [[lagladiators, 0], [lavaliant, 0]], [[lagladiators, 0], [lavaliant, 0]], [none]),
    record(team(shanghai), 0, 2, -5, [[sanfrancisco, 0]], [[sanfrancisco, 0]], [none]),
    record(team(lagladiators), 1, 1, 3, [[lavaliant, 0], [houston, 0]], [[lavaliant, 0], [houston, 0]], [none]),
    record(team(lavaliant), 1, 1, 3, [[lagladiators, 0], [houston, 0]], [[lagladiators, 0], [houston, 0]], [none]),
    record(team(sanfrancisco), 0, 2, -5, [[shanghai, 0]], [[shanghai, 0]], [none]),
    record(team(philadelphia), 0, 2, -3, [none], [none], [none]),
    record(team(florida), 0, 2, -4, [none], [none], [none]),
    record(team(dallas), 0, 2, -1, [none], [none], [none])],
    [(1, [team(london),team(newyork),team(seoul)]), (4, [team(boston)]), (5, [team(houston),team(lagladiators),team(lavaliant)]), (8, [team(dallas)]),
    (9, [team(philadelphia)]), (10, [team(florida)]), (11, [team(sanfrancisco),team(shanghai)])]).
    % Testing tie breakers with a head-to-head map differential breaking a tie
test(teamStandings) :-
    teamStandings([record(team(seoul), 4, 0, 10, [none], [none], [none]),
    record(team(philadelphia), 3, 1, 5, [none], [none], [none]),
    record(team(lavaliant), 3, 1, 3, [none], [none], [none]),
    record(team(london), 3, 1, 9, [[newyork, 1]], [[newyork, 1]], [none]),
    record(team(houston), 2, 2, 0, [[dallas, 0]], [[dallas, 0]], [none]),
    record(team(dallas), 2, 2, 0, [[houston, 0]], [[houston, 0]], [none]),
    record(team(shanghai), 0, 4, -13, [none], [none], [none]),
    record(team(florida), 0, 4, -12, [none], [none], [none]),
    record(team(boston), 1, 3, -8, [none], [none], [none]),
    record(team(newyork), 3, 1, 9, [none], [none], [none]),
    record(team(sanfrancisco), 1, 3, -4, [none], [none], [none]),
    record(team(lagladiators), 2, 2, 4, [none], [none], [none])],
    [(1, [team(seoul)]),
    (2, [team(london)]), 
    (3, [team(newyork)]), 
    (4, [team(philadelphia)]), 
    (5, [team(lavaliant)]), 
    (6, [team(lagladiators)]), 
    (7, [team(dallas), team(houston)]),
    (9, [team(sanfrancisco)]), 
    (10, [team(boston)]), 
    (11, [team(florida)]), 
    (12, [team(shanghai)])]).
    % Test based on the standings at the end of stage 2 in the first season of OWL. No ties
test(teamStandings) :-
    teamStandings([record(team(boston), 6, 4, -1, [[florida, 4], [shanghai, 4], [dallas, 4], [lavaliant, 1], [sanfrancisco, 1], [lagladiators, 1]],
    [[florida, 1], [shanghai, 1], [dallas, 1], [lavaliant, 1], [sanfrancisco, 1], [lagladiators, 1]], [none]),
    record(team(philadelphia), 7, 3, 12, [[boston, 4], [florida, 4], [houston, 1], [shanghai, 4], [dallas, 4], [lagladiators, 2], [lavaliant, 1]], [[boston, 1], [florida, 1], [houston, 1], [shanghai, 1], [dallas, 1], [lagladiators, 1], [lavaliant, 1]], [none]),
    record(team(seoul), 7, 3, 9, [[lavaliant, 4], [sanfrancisco, 2], [dallas, 2], [lagladiators, 2], [shanghai, 2], [philadelphia, 2], [florida, 2]], [[lavaliant, 1], [sanfrancisco, 1], [dallas, 1], [lagladiators, 1], [shanghai, 1], [philadelphia, 1], [florida, 1]],
        [none]),
    record(team(dallas), 2, 8, -15, [[shanghai, 2], [lagladiators, 2]], [[shanghai, 1], [lagladiators, 1]], [none]),
    record(team(lagladiators), 6, 4, 9, [[sanfrancisco, 4], [shanghai, 4], [lavaliant, 4], [london, 2], [houston, 1], [florida, 2]], [[sanfrancisco, 1], [shanghai, 1], [lavaliant, 1], [london, 1], [houston, 1], [florida, 1]], [none]),
    record(team(lavaliant), 4, 6, -5, [[shanghai, 3], [sanfrancisco, 2], [dallas, 2], [houston, 4]], [[shanghai, 1], [sanfrancisco, 1], [dallas, 1], [houston, 1]], [none]),
    record(team(florida), 3, 7, -12, [[lavaliant, 2], [dallas, 1], [sanfrancisco, 1]], [[lavaliant, 1], [dallas, 1], [sanfrancisco, 1]], [none]),
    record(team(london), 8, 2, 20, [[newyork, 1], [florida, 2], [philadelphia, 4], [boston, 4], [sanfrancisco, 2], [seoul, 4], [shanghai, 4], [dallas, 2]], [[newyork, 1], [florida, 1], [philadelphia, 1], [boston, 1], [sanfrancisco, 1], [seoul, 1], [shanghai, 1], [dallas, 1]],
        [none]),
    record(team(sanfrancisco), 3, 7, -7, [[shanghai, 4], [dallas, 3], [houston, 2]], [[shanghai, 1], [dallas, 1], [houston, 1]], [none]),
    record(team(shanghai), 0, 10, -35, [none], [none], [none]),
    record(team(houston), 5, 5, 0, [[london, 1], [boston, 4], [florida, 1], [shanghai, 4], [seoul, 4]], [[london, 1], [boston, 1], [florida, 1], [shanghai, 1], [seoul, 1]], [none]),
    record(team(newyork), 9, 1, 25, [[florida, 2], [boston, 4], [houston, 4], [philadelphia, 2], [sanfrancisco, 4], [seoul, 1], [shanghai, 4], [dallas, 1], [lavaliant, 4]], [[florida, 1], [boston, 1], [houston, 1], [philadelphia, 1], [sanfrancisco, 1],
        [seoul, 1], [shanghai, 1], [dallas, 1], [lavaliant, 1]], [none])],
    [(1, [team(newyork)]),
    (2, [team(london)]),
    (3, [team(philadelphia)]),
    (4, [team(seoul)]),
    (5, [team(lagladiators)]),
    (6, [team(boston)]),
    (7, [team(houston)]),
    (8, [team(lavaliant)]),
    (9, [team(sanfrancisco)]),
    (10, [team(florida)]),
    (11, [team(dallas)]),
    (12, [team(shanghai)])]).
    % Test tie breaking rules by making philadelphia's map differential tie seoul -> seoul should finish third in the standings if that is the case, same thing for florida and sanfrancisco, and for
    % boston and lagladiators
test(teamStandings) :-
    teamStandings([record(team(boston), 6, 4, 3, [[florida, 4], [shanghai, 4], [dallas, 4], [lavaliant, 1], [sanfrancisco, 1], [lagladiators, 2]],
    [[florida, 1], [shanghai, 1], [dallas, 1], [lavaliant, 1], [sanfrancisco, 1], [lagladiators, 1]], [none]),
    record(team(philadelphia), 7, 3, 9, [[boston, 2], [florida, 3], [houston, 1], [shanghai, 4], [dallas, 4], [lagladiators, 2], [lavaliant, 1]], [[boston, 1], [florida, 1], [houston, 1], [shanghai, 1], [dallas, 1], [lagladiators, 1], [lavaliant, 1]], [none]),
    record(team(seoul), 7, 3, 9, [[lavaliant, 4], [sanfrancisco, 2], [dallas, 2], [lagladiators, 2], [shanghai, 2], [philadelphia, 2], [florida, 2]], [[lavaliant, 1], [sanfrancisco, 1], [dallas, 1], [lagladiators, 1], [shanghai, 1], [philadelphia, 1], [florida, 1]],
        [none]),
    record(team(dallas), 2, 8, -18, [[shanghai, 2], [lagladiators, 2]], [[shanghai, 1], [lagladiators, 1]], [none]),
    record(team(lagladiators), 6, 4, 3, [[sanfrancisco, 4], [shanghai, 2], [lavaliant, 4], [london, 2], [houston, 1], [florida, 1]], [[sanfrancisco, 1], [shanghai, 1], [lavaliant, 1], [london, 1], [houston, 1], [florida, 1]], [none]),
    record(team(lavaliant), 4, 6, -5, [[shanghai, 3], [sanfrancisco, 2], [dallas, 2], [houston, 4]], [[shanghai, 1], [sanfrancisco, 1], [dallas, 1], [houston, 1]], [none]),
    record(team(florida), 3, 7, -7, [[lavaliant, 2], [dallas, 4], [sanfrancisco, 1]], [[lavaliant, 2], [dallas, 1], [sanfrancisco, 1]], [none]),
    record(team(london), 8, 2, 20, [[newyork, 1], [florida, 2], [philadelphia, 4], [boston, 4], [sanfrancisco, 2], [seoul, 4], [shanghai, 4], [dallas, 2]], [[newyork, 1], [florida, 1], [philadelphia, 1], [boston, 1], [sanfrancisco, 1], [seoul, 1], [shanghai, 1], [dallas, 1]],
        [none]),
    record(team(sanfrancisco), 3, 7, -7, [[shanghai, 4], [dallas, 3], [houston, 2]], [[shanghai, 1], [dallas, 1], [houston, 1]], [none]),
    record(team(shanghai), 0, 10, -33, [none], [none], [none]),
    record(team(houston), 5, 5, 0, [[london, 1], [boston, 4], [florida, 1], [shanghai, 4], [seoul, 4]], [[london, 1], [boston, 1], [florida, 1], [shanghai, 1], [seoul, 1]], [none]),
    record(team(newyork), 9, 1, 25, [[florida, 2], [boston, 4], [houston, 4], [philadelphia, 2], [sanfrancisco, 4], [seoul, 1], [shanghai, 4], [dallas, 1], [lavaliant, 4]], [[florida, 1], [boston, 1], [houston, 1], [philadelphia, 1], [sanfrancisco, 1],
        [seoul, 1], [shanghai, 1], [dallas, 1], [lavaliant, 1]], [none])],
    [(1, [team(newyork)]),
    (2, [team(london)]),
    (3, [team(seoul)]),
    (4, [team(philadelphia)]),
    (5, [team(boston)]),
    (6, [team(lagladiators)]),
    (7, [team(houston)]),
    (8, [team(lavaliant)]),
    (9, [team(florida)]),
    (10, [team(sanfrancisco)]),
    (11, [team(dallas)]),
    (12, [team(shanghai)])]).
    % boston and lagladiators tie broken by head to head record instead of head to head map differential
test(teamStandings) :-
    teamStandings([record(team(boston), 6, 4, 3, [[florida, 4], [shanghai, 4], [dallas, 4], [lavaliant, 1], [sanfrancisco, 1], [lagladiators, 0]],
    [[florida, 1], [shanghai, 1], [dallas, 1], [lavaliant, 1], [sanfrancisco, 1], [lagladiators, 1]], [none]),
    record(team(philadelphia), 7, 3, 9, [[boston, 2], [florida, 3], [houston, 1], [shanghai, 4], [dallas, 4], [lagladiators, 2], [lavaliant, 1]], [[boston, 1], [florida, 1], [houston, 1], [shanghai, 1], [dallas, 1], [lagladiators, 1], [lavaliant, 1]], [none]),
    record(team(seoul), 7, 3, 9, [[lavaliant, 4], [sanfrancisco, 2], [dallas, 2], [lagladiators, 2], [shanghai, 2], [philadelphia, 2], [florida, 2]], [[lavaliant, 1], [sanfrancisco, 1], [dallas, 1], [lagladiators, 1], [shanghai, 1], [philadelphia, 1], [florida, 1]],
        [none]),
    record(team(dallas), 2, 8, -18, [[shanghai, 2], [lagladiators, 2]], [[shanghai, 1], [lagladiators, 1]], [none]),
    record(team(lagladiators), 6, 4, 3, [[sanfrancisco, 4], [shanghai, 2], [lavaliant, 4], [london, 2], [houston, 1], [florida, 1], [boston, 0]], [[sanfrancisco, 1], [shanghai, 1], [lavaliant, 1], [london, 1], [houston, 1], [florida, 1]], [none]),
    record(team(lavaliant), 4, 6, -5, [[shanghai, 3], [sanfrancisco, 2], [dallas, 2], [houston, 4]], [[shanghai, 1], [sanfrancisco, 1], [dallas, 1], [houston, 1]], [none]),
    record(team(florida), 3, 7, -7, [[lavaliant, 2], [dallas, 4], [sanfrancisco, 1]], [[lavaliant, 2], [dallas, 1], [sanfrancisco, 1]], [none]),
    record(team(london), 8, 2, 20, [[newyork, 1], [florida, 2], [philadelphia, 4], [boston, 4], [sanfrancisco, 2], [seoul, 4], [shanghai, 4], [dallas, 2]], [[newyork, 1], [florida, 1], [philadelphia, 1], [boston, 1], [sanfrancisco, 1], [seoul, 1], [shanghai, 1], [dallas, 1]],
        [none]),
    record(team(sanfrancisco), 3, 7, -7, [[shanghai, 4], [dallas, 3], [houston, 2]], [[shanghai, 1], [dallas, 1], [houston, 1]], [none]),
    record(team(shanghai), 0, 10, -33, [none], [none], [none]),
    record(team(houston), 5, 5, 0, [[london, 1], [boston, 4], [florida, 1], [shanghai, 4], [seoul, 4]], [[london, 1], [boston, 1], [florida, 1], [shanghai, 1], [seoul, 1]], [none]),
    record(team(newyork), 9, 1, 25, [[florida, 2], [boston, 4], [houston, 4], [philadelphia, 2], [sanfrancisco, 4], [seoul, 1], [shanghai, 4], [dallas, 1], [lavaliant, 4]], [[florida, 1], [boston, 1], [houston, 1], [philadelphia, 1], [sanfrancisco, 1],
        [seoul, 1], [shanghai, 1], [dallas, 1], [lavaliant, 1]], [none])],
    [(1, [team(newyork)]),
    (2, [team(london)]),
    (3, [team(seoul)]),
    (4, [team(philadelphia)]),
    (5, [team(boston)]),
    (6, [team(lagladiators)]),
    (7, [team(houston)]),
    (8, [team(lavaliant)]),
    (9, [team(florida)]),
    (10, [team(sanfrancisco)]),
    (11, [team(dallas)]),
    (12, [team(shanghai)])]).
    % seoul and philadelphia tied, boston and lagladiators are tied. No tie-breakers played yet
test(teamStandings) :-
    teamStandings([record(team(boston), 6, 4, 3, [[florida, 4], [shanghai, 4], [dallas, 4], [lavaliant, 1], [sanfrancisco, 1], [lagladiators, 0]],
    [[florida, 1], [shanghai, 1], [dallas, 1], [lavaliant, 1], [sanfrancisco, 1], [lagladiators, 0]], [none]),
    record(team(philadelphia), 7, 3, 9, [[boston, 2], [florida, 3], [houston, 1], [shanghai, 4], [dallas, 4], [lagladiators, 2], [lavaliant, 1], [seoul, 0]], [[boston, 1], [florida, 1], [houston, 1], [shanghai, 1], [dallas, 1], [lagladiators, 1], [lavaliant, 1], [seoul, 0]], [none]),
    record(team(seoul), 7, 3, 9, [[lavaliant, 4], [sanfrancisco, 2], [dallas, 2], [lagladiators, 2], [shanghai, 2], [philadelphia, 0], [florida, 2]], [[lavaliant, 1], [sanfrancisco, 1], [dallas, 1], [lagladiators, 1], [shanghai, 1], [philadelphia, 0], [florida, 1]],
        [none]),
    record(team(dallas), 2, 8, -18, [[shanghai, 2], [lagladiators, 2]], [[shanghai, 1], [lagladiators, 1]], [none]),
    record(team(lagladiators), 6, 4, 3, [[sanfrancisco, 4], [shanghai, 2], [lavaliant, 4], [london, 2], [houston, 1], [florida, 1], [boston, 0]], [[sanfrancisco, 1], [shanghai, 1], [lavaliant, 1], [london, 1], [houston, 1], [florida, 1], [boston, 0]], [none]),
    record(team(lavaliant), 4, 6, -5, [[shanghai, 3], [sanfrancisco, 2], [dallas, 2], [houston, 4]], [[shanghai, 1], [sanfrancisco, 1], [dallas, 1], [houston, 1]], [none]),
    record(team(florida), 3, 7, -7, [[lavaliant, 2], [dallas, 4], [sanfrancisco, 1]], [[lavaliant, 2], [dallas, 1], [sanfrancisco, 1]], [none]),
    record(team(london), 8, 2, 20, [[newyork, 1], [florida, 2], [philadelphia, 4], [boston, 4], [sanfrancisco, 2], [seoul, 4], [shanghai, 4], [dallas, 2]], [[newyork, 1], [florida, 1], [philadelphia, 1], [boston, 1], [sanfrancisco, 1], [seoul, 1], [shanghai, 1], [dallas, 1]],
        [none]),
    record(team(sanfrancisco), 3, 7, -7, [[shanghai, 4], [dallas, 3], [houston, 2]], [[shanghai, 1], [dallas, 1], [houston, 1]], [none]),
    record(team(shanghai), 0, 10, -33, [none], [none], [none]),
    record(team(houston), 5, 5, 0, [[london, 1], [boston, 4], [florida, 1], [shanghai, 4], [seoul, 4]], [[london, 1], [boston, 1], [florida, 1], [shanghai, 1], [seoul, 1]], [none]),
    record(team(newyork), 9, 1, 25, [[florida, 2], [boston, 4], [houston, 4], [philadelphia, 2], [sanfrancisco, 4], [seoul, 1], [shanghai, 4], [dallas, 1], [lavaliant, 4]], [[florida, 1], [boston, 1], [houston, 1], [philadelphia, 1], [sanfrancisco, 1],
        [seoul, 1], [shanghai, 1], [dallas, 1], [lavaliant, 1]], [none])],
    [(1, [team(newyork)]),
    (2, [team(london)]),
    (3, [team(philadelphia),team(seoul)]),
    (5, [team(boston),team(lagladiators)]),
    (7, [team(houston)]),
    (8, [team(lavaliant)]),
    (9, [team(florida)]),
    (10, [team(sanfrancisco)]),
    (11, [team(dallas)]),
    (12, [team(shanghai)])]).
    % ties set up in previous test broken by special tie-breaker matches
    % TODO: set up tie breakers
test(teamStandings) :-
    teamStandings([record(team(boston), 6, 4, 3, [[florida, 4], [shanghai, 4], [dallas, 4], [lavaliant, 1], [sanfrancisco, 1], [lagladiators, 0]],
    [[florida, 1], [shanghai, 1], [dallas, 1], [lavaliant, 1], [sanfrancisco, 1], [lagladiators, 0]], [lagladiators]),
    record(team(philadelphia), 7, 3, 9, [[boston, 2], [florida, 3], [houston, 1], [shanghai, 4], [dallas, 4], [lagladiators, 2], [lavaliant, 1], [seoul, 0]], [[boston, 1], [florida, 1], [houston, 1], [shanghai, 1], [dallas, 1], [lagladiators, 1], [lavaliant, 1], [seoul, 0]], [seoul]),
    record(team(seoul), 7, 3, 9, [[lavaliant, 4], [sanfrancisco, 2], [dallas, 2], [lagladiators, 2], [shanghai, 2], [philadelphia, 0], [florida, 2]], [[lavaliant, 1], [sanfrancisco, 1], [dallas, 1], [lagladiators, 1], [shanghai, 1], [philadelphia, 0], [florida, 1]],
        [none]),
    record(team(dallas), 2, 8, -18, [[shanghai, 2], [lagladiators, 2]], [[shanghai, 1], [lagladiators, 1]], [none]),
    record(team(lagladiators), 6, 4, 3, [[sanfrancisco, 4], [shanghai, 2], [lavaliant, 4], [london, 2], [houston, 1], [florida, 1], [boston, 0]], [[sanfrancisco, 1], [shanghai, 1], [lavaliant, 1], [london, 1], [houston, 1], [florida, 1], [boston, 0]], [none]),
    record(team(lavaliant), 4, 6, -5, [[shanghai, 3], [sanfrancisco, 2], [dallas, 2], [houston, 4]], [[shanghai, 1], [sanfrancisco, 1], [dallas, 1], [houston, 1]], [none]),
    record(team(florida), 3, 7, -7, [[lavaliant, 2], [dallas, 4], [sanfrancisco, 1]], [[lavaliant, 2], [dallas, 1], [sanfrancisco, 1]], [none]),
    record(team(london), 8, 2, 20, [[newyork, 1], [florida, 2], [philadelphia, 4], [boston, 4], [sanfrancisco, 2], [seoul, 4], [shanghai, 4], [dallas, 2]], [[newyork, 1], [florida, 1], [philadelphia, 1], [boston, 1], [sanfrancisco, 1], [seoul, 1], [shanghai, 1], [dallas, 1]],
        [none]),
    record(team(sanfrancisco), 3, 7, -7, [[shanghai, 4], [dallas, 3], [houston, 2]], [[shanghai, 1], [dallas, 1], [houston, 1]], [none]),
    record(team(shanghai), 0, 10, -33, [none], [none], [none]),
    record(team(houston), 5, 5, 0, [[london, 1], [boston, 4], [florida, 1], [shanghai, 4], [seoul, 4]], [[london, 1], [boston, 1], [florida, 1], [shanghai, 1], [seoul, 1]], [none]),
    record(team(newyork), 9, 1, 25, [[florida, 2], [boston, 4], [houston, 4], [philadelphia, 2], [sanfrancisco, 4], [seoul, 1], [shanghai, 4], [dallas, 1], [lavaliant, 4]], [[florida, 1], [boston, 1], [houston, 1], [philadelphia, 1], [sanfrancisco, 1],
        [seoul, 1], [shanghai, 1], [dallas, 1], [lavaliant, 1]], [none])],
    [(1, [team(newyork)]),
    (2, [team(london)]),
    (3, [team(philadelphia)]),
    (4, [team(seoul)]),
    (5, [team(boston)]),
    (6, [team(lagladiators)]),
    (7, [team(houston)]),
    (8, [team(lavaliant)]),
    (9, [team(florida)]),
    (10, [team(sanfrancisco)]),
    (11, [team(dallas)]),
    (12, [team(shanghai)])]).


tester() :- teamStandings([record(team(newyork), 2, 0, 6, [[london, 0], [seoul, 0]], [[london, 0], [seoul, 0]], [none]),
record(team(london), 2, 0, 6, [[newyork, 0], [seoul, 0]], [[newyork, 0], [seoul, 0]], [none]),
record(team(seoul), 2, 0, 6, [[newyork, 0], [london, 0]], [[newyork, 0], [london, 0]], [none]),
record(team(boston), 2, 0, 4, [none], [none], [none]),
record(team(houston), 1, 1, 3, [[lagladiators, 0], [lavaliant, 0]], [[lagladiators, 0], [lavaliant, 0]], [none]),
record(team(shanghai), 0, 2, -5, [[sanfrancisco, 0]], [[sanfrancisco, 0]], [none]),
record(team(lagladiators), 1, 1, 3, [[lavaliant, 0], [houston, 0]], [[lavaliant, 0], [houston, 0]], [none]),
record(team(lavaliant), 1, 1, 3, [[lagladiators, 0], [houston, 0]], [[lagladiators, 0], [houston, 0]], [none]),
record(team(sanfrancisco), 0, 2, -5, [[shanghai, 0]], [[shanghai, 0]], [none]),
record(team(philadelphia), 0, 2, -3, [none], [none], [none]),
record(team(florida), 0, 2, -4, [none], [none], [none]),
record(team(dallas), 0, 2, -1, [none], [none], [none])], X), print(X).


:- end_tests('../../prolog/stage-structure').
